#!/bin/bash
# Run script for SMTInterpol for SMT-COMP 2024+ for bitvector theories
SCRIPTDIR=`dirname $0`
java -da -dsa -jar $SCRIPTDIR/smtinterpol.jar -w -o continue-on-error=false -o proof-check-mode -o model-check-mode "$@" 2>error.log
